### ISSUE TITLE
Database gone on timeout

### ISSUE THREAD

**Issue by collymore** [nemke82/magento2gitpod#3]
After the workspace times out the database has gone.
I had a working frontend and admin but after opening the workspace after trying to start it again, I wasn't able to get it working again. 
Is there a preferred way of managing this? 
Do you have to reinstall Magento each time you open the workspace?

**Comment by nemke82** [comment]
Dear @collymore. Thanks for reporting this. Yeah, so far I just n98-magerun2 db:dump export SQL file to /app/etc/ directory or somewhere else so when i times out files/folders are back, but yeah I have to create database and import SQL file. 

Maybe if I put MySQL under /workspace/magento2gitpod that won't go ephemeral. Might test that, no problem. Let me know if you have any other suggestions or recommendations.
